#!/bin/bash

# Start GTD is the work performed. If empty, it is set as IN
meeting_name="${1,,}"
meeting_name="${meeting_name^}"

if [ $# -eq 0 ]
then
    meeting_name=IN
fi

if [[ -v ESCALE_ENV ]]
then
    toggl start --project GTD --tags 'Meta Work',Escale,Work "${meeting_name}"
else
    toggl start --project GTD --tags 'Meta Work',Work "${meeting_name}"
fi
